### ISSUE TITLE
xml_parsing() - zbxTelegram.py:96 - ERROR: Exception occurred: syntax error: line 1, column 0

### ISSUE THREAD

**Issue by A-Kod** [xxsokolov/Zabbix-Notification-Telegram#12]
Приветствую!
Прошу помощи с ошибкой. Дебаг запустил, вот лог (имя пользователя заменил).

![1E0A1596-9436-42B1-9AD1-2BD4012274D6](https://user-images.githubusercontent.com/17290512/74306266-22e17480-4d73-11ea-8c98-aacf1434a1ca.jpeg)

**Comment by xxsokolov** [comment]
Привет, включай дебаг и скидывай лог, ток замаж токен и юзернэйм.

config_debug_mode = True
config_exc_info = True

**Comment by A-Kod** [comment]
Нужен другой лог, не тот, который в файле znt.log?

**Comment by xxsokolov** [comment]
именно он и нужен, при включении опций указанных выше, лог станет более подробный

**Comment by A-Kod** [comment]
Дело в том, что я уже заменил в файле zbxTelegram_config.example значения на 

config_debug_mode = True
config_exc_info = True

И на скрине все, что было в логе.

**Comment by xxsokolov** [comment]
Default message
Для настройки оповещения используется XML разметка (Исходные данные Вы найдете в actions.example)

**Comment by A-Kod** [comment]
Разобрался. Большое спасибо за помощь!
