### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by A-Kod** [xxsokolov/Zabbix-Notification-Telegram#15]
Приветствую!

Не совсем понял, каким образом конфигурируется прокси.
У меня есть строчка с настройками прокси-сервера в формате:
https://t.me/proxy?server=[ip-адрес]&port=[номер порта]&secret=[секрет]. 
Как понял, в файлах конфигурации zbxTelegram_config.py и znt_config.py необходимо скорректировать  следующие строки:

tg_proxy = True
tg_proxy_server = {'https': 'socks5://username:password@domen:port'}

Но как именно указать tg_proxy_server не совсем понятно. 
Пробовал в формате 
tg_proxy_server  = {'https': 'https://t.me/proxy?server=[ip-адрес]&port=[номер порта]&secret=[секрет]'} - не получилось. 

В znt.log вижу следующую ошибку:
requests.exeptions.ProxyError: HTTPSConnectionPool (host= 'api.telegram.org', port=443):[токен]/sendMediaGroup?chat_id=[ID чата]&media=[...] (proxy.', OSError('Tunnel connection failed: 400 Bad Request',)))

**Comment by xxsokolov** [comment]
Я так понимаю обсудили в группе TG

**Comment by A-Kod** [comment]
Да, спасибо!

**Comment by Vedemon** [comment]
А можно решение сюда? Mtproto есть, но вот как завернуть туда запросы? Это ж не socks5
