### ISSUE TITLE
Можно ли тегать людей при сообщениях об аварии от Бота 

### ISSUE THREAD

**Issue by clagami** [xxsokolov/Zabbix-Notification-Telegram#28]
Пример

✅ Warning ⚠️ High swap space usage ( less than 50% free)

Сервер: Zabbix server [1.1.1.1]
Зафиксировано: (12:00:00)
Последнее значение: 50.44 %
Описание: Сервер мониторинга на базе Zabbix 5
Продолжительность: 5m
@Username

**Comment by clagami** [comment]
Чуть чуть поковырялся и получилось вот это вот 

if tags:
                    if tags.find(':') != -1:
                        tag, value = tags.split(':')
                        tags_list.append('{tag} {value}'.format(tag=re.sub(r"\W+", "_", tag),
                                                                 value=re.sub(r"\W+", "@", value)))


но это чисто в моём кейсе, не тестил со всеми тегами

**Comment by xxsokolov** [comment]
Done
