### ISSUE TITLE
ERROR: Exception occurred: too many values to unpack 

### ISSUE THREAD

**Issue by mbgh0st** [xxsokolov/Zabbix-Notification-Telegram#34]
Добрый день! С прошлой недели стали вылезать разные ошибки и примерно не отправляется 7-8 сообщения из 10, одна из них, до этого все норм работало. (Ничего не менял)
![Screenshot_1](https://user-images.githubusercontent.com/87126744/133036968-060bbe82-b4e9-4f68-96c6-f6e63b00c74f.png)

**Comment by pmishka** [comment]
Подтверждаю, постоянно осыпается на отправке по триггеру свободного места на диске

**Comment by Anvill1** [comment]
Fix - https://github.com/xxsokolov/Zabbix-Notification-Telegram/pull/47

**Comment by xxsokolov** [comment]
https://github.com/xxsokolov/Zabbix-Notification-Telegram/issues/34#issuecomment-1301840261

Approve

**Comment by xxsokolov** [comment]
https://t.me/ZbxNTg
