### ISSUE TITLE
Добавить возможность description в уведомлениях

### ISSUE THREAD

**Issue by legolego621** [xxsokolov/Zabbix-Notification-Telegram#39]
Добрый день. Вы создали очень полезный инструмент уведомлений, конкурирующий с всем известным zbxtg.
Не хватает возможности отображения description в отсылаемых уведомлениях.
Если есть возможность и время - добавьте пожалуйста.

**Comment by legolego621** [comment]
Может кому-то пригодиться - Description (как и многое другое) можно передать напрямую из переменных заббикса в теле шаблона сообщений в способе оповещаний.

```
Host: {HOST.HOST} [{HOST.IP}]
Description trigger: {TRIGGER.DESCRIPTION}
Last value: {ITEM.LASTVALUE1} ({TIME})
Duration: {EVENT.AGE}]]>
```


![image](https://user-images.githubusercontent.com/18234639/144738139-23b0dc46-866c-4033-9c23-906dfaf3761a.png)

**Comment by xxsokolov** [comment]
https://t.me/ZbxNTg
