### ISSUE TITLE
Проблема авторизации при проверке пользовательских сертфиикатов

### ISSUE THREAD

**Issue by RomanBogachev** [xxsokolov/Zabbix-Notification-Telegram#40]
Приветствую! 

В NGINX настроена авторизация через пользовательские сертификаты для доступа к веб-интерфейсу Zabbix.
Графики при этом не отправляются в Telegram, потому что не проходит авторизацию пользователь, так как не удаётся проверить клиентский сертификат. В конфигурационном файле такая опция  отсутствует.

Как можно решить проблему?

**Comment by iharkoushal** [comment]
Такая же проблема. После установки работы через SSL - перестают графики отправляться.

**Comment by addrian1** [comment]
Привет!
Можете попросить nginx слушать 80й порт для zabbix'а на localhost (если скрипт находится там же хосте) и подключить [Zabbix-Notification-Telegram](https://github.com/xxsokolov/Zabbix-Notification-Telegram) по 80му порту. Трафик все равно локальный. Но есть одно но - кнопки в уведомлениях тогда тоже будут отправльять на 80й порт. 
Все же, в конечно итоге, порекомендовал бы воспользоваться certbot для получения валидируемого сертификата.

**Comment by xxsokolov** [comment]
https://github.com/xxsokolov/Zabbix-Notification-Telegram
