### ISSUE TITLE
Ошибка при тестовой попытке

### ISSUE THREAD

**Issue by Artem-Mamzikov** [xxsokolov/Zabbix-Notification-Telegram#41]
debian 9 stretch
python3-venv (3.5.3-1)
pip install wheel
pip install pyTelegramBotAPI
pip install pillow
pip install pysocks
pip install xmltodict

Делал все по инструкции
[https://github.com/xxsokolov/Zabbix-Notification-Telegram/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BD%D0%BE%D1%82%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D0%B0-Zabbix-Notification-Telegram](url)

При тестовой попытке получаю такую ошибку
./zbxTelegram.py @имя test test

Traceback (most recent call last):
  File "/usr/local/share/zabbix/alertscripts/Zabbix-Notification-Telegram/zbxTelegram.py", line 12, in <module>
    import telebot
  File "/usr/local/share/zabbix/alertscripts/venv/lib/python3.5/site-packages/telebot/__init__.py", line 575
    e.args = e.args + (f'Typed middleware handler "{typed_middleware_handler.__qualname__}"',)
                                                                                           ^
SyntaxError: invalid syntax

Как можно решить данную ошибку ?

**Comment by Artem-Mamzikov** [comment]
Данный вопрос решил, установил python3.9.9 из исходного кода.
Пробовал версию 3.10.1 работает , но не работает ssl и не дает ничего загрузить. Просит OpenSSL 1.1.1 у меня же 1.1.0.из исходного когда ставит не захотел openssl , откатился на 3.9.9 все работает.
Минимальная версия для работы данного плагина на сколько я понял 3.6, у меня же была последняя доступная из репозитория 3.5

**Comment by xxsokolov** [comment]
https://t.me/ZbxNTg
