### ISSUE TITLE
ERROR: Exception occurred: No XML in zabbix actions or it's not valid (xml parsing error). XML: out of memory: line 1, column 0

### ISSUE THREAD

**Issue by EugeneLVB** [xxsokolov/Zabbix-Notification-Telegram#42]
Привет!

Неожиданно перестали приходить уведомления.
Тестовые уведомления отрабатывают.
Потребления памяти не наблюдается.

Zabbix 5.4.10
debug log:

```sh
[2022-02-23 13:40:12,814] - PID:2279755 - xml_parsing() - zbxTelegram.py:129 - ERROR: Exception occurred: No XML in zabbix actions or it's not valid (xml parsing error). XML: out of memory: line 1, column 0
Traceback (most recent call last):
  File "/usr/lib/zabbix/alertscripts/zbxTelegram.py", line 73, in xml_parsing
    data = dict(xmltodict.parse(data, process_namespaces=True)['root'])
  File "/usr/lib/zabbix/alertscripts/venv/lib/python3.8/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: out of memory: line 1, column 0
```

**Comment by EugeneLVB** [comment]
Проблема относиться к пакету [libexpat1](https://bugs.launchpad.net/ubuntu/+source/expat/+bug/1961800)

Решение для focal:
apt install libexpat1=2.2.9-1build1

**Comment by EugeneLVB** [comment]
Проблема относиться к пакету [libexpat1](https://bugs.launchpad.net/ubuntu/+source/expat/+bug/1961800)

Решение для focal:

```
apt install libexpat1=2.2.9-1build1
```

**Comment by soloduy1** [comment]
На Ubuntu 18.04 помогло

sudo apt-get install libexpat1=2.2.5-3 libexpat1-dev=2.2.5-3

**Comment by xxsokolov** [comment]
https://github.com/xxsokolov/Zabbix-Notification-Telegram

**Comment by Ursadon** [comment]
Для импортозамещённых: на РедОС 7.3.2 - `dnf install expat expat-static`
