### ISSUE TITLE
ERROR: xml_parsing() - zbxTelegram.py:130 - ERROR: Exception occurred: No XML in zabbix actions or it's not valid (xml parsing error). XML: 'utf-8' codec can't encode character '\udcb0' in position 146: surrogates not allowed

### ISSUE THREAD

**Issue by RomanBogachev** [xxsokolov/Zabbix-Notification-Telegram#43]
Zabbix 6.0.0

Error `xml_parsing() - zbxTelegram.py:130 - ERROR: Exception occurred: No XML in zabbix actions or it's not valid (xml parsing error). XML: 'utf-8' codec can't encode character '\udcb0' in position 146: surrogates not allowed` and graphs doesn`t send.

**Comment by xxsokolov** [comment]
https://github.com/xxsokolov/Zabbix-Notification-Telegram
